/**
 * Design Token Extractor
 * Extracts design tokens from CSS files (specifically from James's portfolio)
 */

import type {
  DesignStyle,
  DesignMood,
  FontCategory,
  ParsedColors,
  ParsedTypography,
} from './schema';

/**
 * Extracted theme data from portfolio
 * Pre-extracted from portfolio theme CSS
 */
export interface ExtractedTheme {
  name: string;
  label: string;
  style: DesignStyle;
  mood: DesignMood;
  description: string;
  colors: {
    background: string;
    foreground: string;
    card: string;
    cardForeground: string;
    primary: string;
    primaryForeground: string;
    secondary: string;
    secondaryForeground: string;
    muted: string;
    mutedForeground: string;
    accent: string;
    accentForeground: string;
    border: string;
    ring: string;
  };
  typography: {
    fontFamily: string;
    headingFont: string;
    category: FontCategory;
  };
  tags: string[];
}

/**
 * Pre-extracted themes from James's Portfolio
 * Manually curated with style/mood classification
 */
export const EXTRACTED_THEMES: ExtractedTheme[] = [
  // AI/Tech Company Themes
  {
    name: 'claude',
    label: 'Claude',
    style: 'minimal',
    mood: 'warm',
    description: 'Anthropic Claude AI interface - warm terracotta orange with clean typography',
    colors: {
      background: '30 20% 98%',
      foreground: '20 14% 10%',
      card: '30 30% 96%',
      cardForeground: '20 14% 10%',
      primary: '24 90% 55%',
      primaryForeground: '0 0% 100%',
      secondary: '30 20% 90%',
      secondaryForeground: '20 14% 20%',
      muted: '30 15% 92%',
      mutedForeground: '20 10% 40%',
      accent: '24 80% 60%',
      accentForeground: '0 0% 100%',
      border: '30 20% 85%',
      ring: '24 90% 55%',
    },
    typography: {
      fontFamily: '"Söhne", ui-sans-serif, system-ui, sans-serif',
      headingFont: '"Söhne", ui-sans-serif, system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['ai', 'anthropic', 'warm', 'orange', 'conversational', 'assistant'],
  },
  {
    name: 'chatgpt',
    label: 'ChatGPT',
    style: 'minimal',
    mood: 'professional',
    description: 'OpenAI ChatGPT interface - clean with teal accent',
    colors: {
      background: '0 0% 98%',
      foreground: '0 0% 10%',
      card: '0 0% 100%',
      cardForeground: '0 0% 10%',
      primary: '161 23% 45%',
      primaryForeground: '0 0% 100%',
      secondary: '0 0% 94%',
      secondaryForeground: '0 0% 20%',
      muted: '0 0% 92%',
      mutedForeground: '0 0% 40%',
      accent: '161 23% 45%',
      accentForeground: '0 0% 100%',
      border: '0 0% 85%',
      ring: '161 23% 45%',
    },
    typography: {
      fontFamily: '"OpenAI Sans", "Söhne", ui-sans-serif, system-ui, sans-serif',
      headingFont: '"OpenAI Sans", "Söhne", ui-sans-serif, system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['ai', 'openai', 'teal', 'chat', 'conversational', 'clean'],
  },
  {
    name: 'vercel',
    label: 'Vercel',
    style: 'minimal',
    mood: 'professional',
    description: 'Vercel - Ultra clean black and white with Geist font',
    colors: {
      background: '0 0% 100%',
      foreground: '0 0% 5%',
      card: '0 0% 98%',
      cardForeground: '0 0% 5%',
      primary: '0 0% 5%',
      primaryForeground: '0 0% 100%',
      secondary: '0 0% 95%',
      secondaryForeground: '0 0% 10%',
      muted: '0 0% 96%',
      mutedForeground: '0 0% 40%',
      accent: '0 0% 5%',
      accentForeground: '0 0% 100%',
      border: '0 0% 90%',
      ring: '0 0% 5%',
    },
    typography: {
      fontFamily: '"Geist", Inter, system-ui, sans-serif',
      headingFont: '"Geist", Inter, system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['tech', 'minimal', 'monochrome', 'developer', 'clean', 'modern'],
  },
  {
    name: 'cursor',
    label: 'Cursor',
    style: 'tech',
    mood: 'tech',
    description: 'Cursor AI code editor - teal and purple with monospace',
    colors: {
      background: '220 14% 96%',
      foreground: '240 6% 10%',
      card: '220 14% 98%',
      cardForeground: '240 6% 10%',
      primary: '173 80% 40%',
      primaryForeground: '0 0% 100%',
      secondary: '220 13% 91%',
      secondaryForeground: '240 6% 15%',
      muted: '220 10% 94%',
      mutedForeground: '220 9% 40%',
      accent: '262 83% 58%',
      accentForeground: '0 0% 100%',
      border: '220 13% 86%',
      ring: '173 80% 40%',
    },
    typography: {
      fontFamily: '"JetBrains Mono", "Fira Code", "SF Mono", monospace',
      headingFont: '"Inter", -apple-system, BlinkMacSystemFont, system-ui, sans-serif',
      category: 'monospace',
    },
    tags: ['tech', 'code', 'editor', 'purple', 'teal', 'developer', 'ai'],
  },

  // Corporate/Brand Themes
  {
    name: 'google',
    label: 'Google',
    style: 'corporate',
    mood: 'professional',
    description: 'Material Design 3 - Google Blue with rounded corners',
    colors: {
      background: '0 0% 100%',
      foreground: '214 9% 15%',
      card: '210 20% 98%',
      cardForeground: '214 9% 15%',
      primary: '217 90% 61%',
      primaryForeground: '0 0% 100%',
      secondary: '210 20% 95%',
      secondaryForeground: '214 9% 20%',
      muted: '210 16% 93%',
      mutedForeground: '214 5% 45%',
      accent: '142 53% 43%',
      accentForeground: '0 0% 100%',
      border: '210 14% 89%',
      ring: '217 90% 61%',
    },
    typography: {
      fontFamily: '"Google Sans", "Roboto", system-ui, sans-serif',
      headingFont: '"Google Sans Display", "Google Sans", "Roboto", system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['corporate', 'material', 'blue', 'google', 'professional', 'brand'],
  },
  {
    name: 'apple',
    label: 'Apple',
    style: 'elegant',
    mood: 'professional',
    description: 'Human Interface Guidelines - iOS Blue with SF Pro',
    colors: {
      background: '0 0% 100%',
      foreground: '0 0% 0%',
      card: '0 0% 98%',
      cardForeground: '0 0% 0%',
      primary: '211 100% 50%',
      primaryForeground: '0 0% 100%',
      secondary: '220 10% 94%',
      secondaryForeground: '0 0% 20%',
      muted: '220 8% 96%',
      mutedForeground: '0 0% 45%',
      accent: '211 100% 50%',
      accentForeground: '0 0% 100%',
      border: '220 10% 88%',
      ring: '211 100% 50%',
    },
    typography: {
      fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", "Helvetica Neue", system-ui, sans-serif',
      headingFont: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "Helvetica Neue", system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['corporate', 'apple', 'ios', 'blue', 'elegant', 'premium', 'brand'],
  },
  {
    name: 'microsoft',
    label: 'Microsoft',
    style: 'corporate',
    mood: 'professional',
    description: 'Fluent Design System - Windows Blue with Segoe UI',
    colors: {
      background: '0 0% 100%',
      foreground: '0 0% 11%',
      card: '0 0% 98%',
      cardForeground: '0 0% 11%',
      primary: '206 100% 42%',
      primaryForeground: '0 0% 100%',
      secondary: '210 14% 93%',
      secondaryForeground: '0 0% 20%',
      muted: '210 11% 96%',
      mutedForeground: '0 0% 44%',
      accent: '206 100% 42%',
      accentForeground: '0 0% 100%',
      border: '210 14% 89%',
      ring: '206 100% 42%',
    },
    typography: {
      fontFamily: '"Segoe UI Variable", "Segoe UI", -apple-system, BlinkMacSystemFont, system-ui, sans-serif',
      headingFont: '"Segoe UI Variable Display", "Segoe UI", -apple-system, BlinkMacSystemFont, system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['corporate', 'microsoft', 'fluent', 'blue', 'windows', 'brand'],
  },
  {
    name: 'notion',
    label: 'Notion',
    style: 'minimal',
    mood: 'professional',
    description: 'Block-based workspace - minimal with subtle warmth',
    colors: {
      background: '0 0% 100%',
      foreground: '0 0% 9%',
      card: '0 0% 100%',
      cardForeground: '0 0% 9%',
      primary: '0 0% 9%',
      primaryForeground: '0 0% 100%',
      secondary: '45 33% 97%',
      secondaryForeground: '0 0% 20%',
      muted: '45 10% 94%',
      mutedForeground: '0 0% 45%',
      accent: '210 100% 65%',
      accentForeground: '0 0% 100%',
      border: '0 0% 90%',
      ring: '0 0% 9%',
    },
    typography: {
      fontFamily: '"Inter", ui-sans-serif, -apple-system, BlinkMacSystemFont, system-ui, sans-serif',
      headingFont: '"Inter", ui-sans-serif, -apple-system, BlinkMacSystemFont, system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['productivity', 'minimal', 'workspace', 'clean', 'notes', 'brand'],
  },
  {
    name: 'miro',
    label: 'Miro',
    style: 'playful',
    mood: 'creative',
    description: 'Collaborative canvas - bright yellow accent',
    colors: {
      background: '0 0% 98%',
      foreground: '0 0% 12%',
      card: '0 0% 100%',
      cardForeground: '0 0% 12%',
      primary: '51 100% 48%',
      primaryForeground: '0 0% 0%',
      secondary: '220 14% 96%',
      secondaryForeground: '0 0% 20%',
      muted: '220 10% 94%',
      mutedForeground: '0 0% 45%',
      accent: '220 90% 56%',
      accentForeground: '0 0% 100%',
      border: '220 13% 91%',
      ring: '51 100% 48%',
    },
    typography: {
      fontFamily: '"Inter", "Work Sans", ui-sans-serif, system-ui, sans-serif',
      headingFont: '"Inter", "Work Sans", ui-sans-serif, system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['collaboration', 'yellow', 'whiteboard', 'creative', 'canvas', 'brand'],
  },

  // Nature/Organic Themes
  {
    name: 'kodama-grove',
    label: 'Kodama Grove',
    style: 'nature',
    mood: 'calm',
    description: 'Forest green nature theme - inspired by Studio Ghibli',
    colors: {
      background: '120 20% 97%',
      foreground: '120 30% 10%',
      card: '120 25% 94%',
      cardForeground: '120 30% 10%',
      primary: '142 70% 35%',
      primaryForeground: '0 0% 100%',
      secondary: '120 20% 88%',
      secondaryForeground: '120 30% 15%',
      muted: '120 15% 90%',
      mutedForeground: '120 15% 40%',
      accent: '142 60% 40%',
      accentForeground: '0 0% 100%',
      border: '120 20% 82%',
      ring: '142 70% 35%',
    },
    typography: {
      fontFamily: '"Nunito", "Quicksand", system-ui, sans-serif',
      headingFont: '"Nunito", "Quicksand", system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['nature', 'forest', 'green', 'organic', 'calm', 'ghibli', 'japanese'],
  },
  {
    name: 'sage-garden',
    label: 'Sage Garden',
    style: 'nature',
    mood: 'calm',
    description: 'Earthy sage greens - botanical aesthetic',
    colors: {
      background: '45 22% 96%',
      foreground: '225 28% 14%',
      card: '0 0% 100%',
      cardForeground: '225 28% 14%',
      primary: '138 8% 53%',
      primaryForeground: '0 0% 100%',
      secondary: '80 20% 80%',
      secondaryForeground: '225 28% 14%',
      muted: '45 15% 91%',
      mutedForeground: '0 0% 44%',
      accent: '80 15% 75%',
      accentForeground: '225 28% 14%',
      border: '45 15% 91%',
      ring: '138 8% 53%',
    },
    typography: {
      fontFamily: '"Antic", system-ui, sans-serif',
      headingFont: '"Antic", system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['nature', 'sage', 'botanical', 'earthy', 'calm', 'organic'],
  },
  {
    name: 'nature',
    label: 'Nature',
    style: 'nature',
    mood: 'warm',
    description: 'Earth tones with olive green and warm browns',
    colors: {
      background: '45 25% 96%',
      foreground: '30 30% 12%',
      card: '45 30% 92%',
      cardForeground: '30 30% 12%',
      primary: '85 50% 40%',
      primaryForeground: '0 0% 100%',
      secondary: '45 20% 85%',
      secondaryForeground: '30 30% 18%',
      muted: '45 15% 88%',
      mutedForeground: '30 20% 45%',
      accent: '30 60% 50%',
      accentForeground: '0 0% 100%',
      border: '45 20% 78%',
      ring: '85 50% 40%',
    },
    typography: {
      fontFamily: '"Lora", "Merriweather", Georgia, serif',
      headingFont: '"Lora", "Merriweather", Georgia, serif',
      category: 'serif',
    },
    tags: ['nature', 'earthy', 'olive', 'brown', 'organic', 'warm'],
  },

  // Elegant/Luxury Themes
  {
    name: 'elegant-luxury',
    label: 'Elegant Luxury',
    style: 'elegant',
    mood: 'warm',
    description: 'Gold accents with sophisticated typography',
    colors: {
      background: '40 20% 98%',
      foreground: '30 30% 12%',
      card: '40 25% 96%',
      cardForeground: '30 30% 12%',
      primary: '45 80% 50%',
      primaryForeground: '40 20% 98%',
      secondary: '40 15% 92%',
      secondaryForeground: '30 30% 18%',
      muted: '40 12% 94%',
      mutedForeground: '30 20% 45%',
      accent: '45 90% 55%',
      accentForeground: '40 20% 98%',
      border: '40 15% 88%',
      ring: '45 80% 50%',
    },
    typography: {
      fontFamily: '"Cormorant Garamond", "Times New Roman", Georgia, serif',
      headingFont: '"Cormorant Garamond", "Times New Roman", Georgia, serif',
      category: 'serif',
    },
    tags: ['luxury', 'gold', 'elegant', 'premium', 'sophisticated', 'serif'],
  },
  {
    name: 'perpetuity',
    label: 'Perpetuity',
    style: 'elegant',
    mood: 'professional',
    description: 'Monochrome elegance with classic typography',
    colors: {
      background: '0 0% 98%',
      foreground: '0 0% 8%',
      card: '0 0% 95%',
      cardForeground: '0 0% 8%',
      primary: '0 0% 15%',
      primaryForeground: '0 0% 98%',
      secondary: '0 0% 88%',
      secondaryForeground: '0 0% 15%',
      muted: '0 0% 90%',
      mutedForeground: '0 0% 45%',
      accent: '0 0% 25%',
      accentForeground: '0 0% 98%',
      border: '0 0% 82%',
      ring: '0 0% 15%',
    },
    typography: {
      fontFamily: '"EB Garamond", "Garamond", "Times New Roman", serif',
      headingFont: '"EB Garamond", "Garamond", "Times New Roman", serif',
      category: 'serif',
    },
    tags: ['monochrome', 'elegant', 'timeless', 'classic', 'serif', 'minimal'],
  },
  {
    name: 'vintage-paper',
    label: 'Vintage Paper',
    style: 'retro',
    mood: 'warm',
    description: 'Sepia-toned aged paper aesthetic',
    colors: {
      background: '40 30% 95%',
      foreground: '30 20% 15%',
      card: '40 35% 92%',
      cardForeground: '30 20% 15%',
      primary: '30 50% 35%',
      primaryForeground: '40 30% 95%',
      secondary: '40 25% 85%',
      secondaryForeground: '30 20% 20%',
      muted: '40 20% 88%',
      mutedForeground: '30 15% 45%',
      accent: '30 60% 45%',
      accentForeground: '40 30% 95%',
      border: '40 25% 78%',
      ring: '30 50% 35%',
    },
    typography: {
      fontFamily: '"Courier Prime", "Courier New", Courier, monospace',
      headingFont: '"Playfair Display", "Times New Roman", Georgia, serif',
      category: 'monospace',
    },
    tags: ['vintage', 'sepia', 'retro', 'paper', 'nostalgic', 'typewriter'],
  },

  // Bold/Creative Themes
  {
    name: 'neo-brutalism',
    label: 'Neo Brutalism',
    style: 'bold',
    mood: 'dramatic',
    description: 'High contrast, bold shadows, raw aesthetic',
    colors: {
      background: '60 100% 97%',
      foreground: '0 0% 0%',
      card: '0 0% 100%',
      cardForeground: '0 0% 0%',
      primary: '0 0% 0%',
      primaryForeground: '60 100% 97%',
      secondary: '60 100% 85%',
      secondaryForeground: '0 0% 0%',
      muted: '60 50% 90%',
      mutedForeground: '0 0% 30%',
      accent: '350 100% 60%',
      accentForeground: '0 0% 100%',
      border: '0 0% 0%',
      ring: '0 0% 0%',
    },
    typography: {
      fontFamily: '"Space Grotesk", "Space Mono", Impact, sans-serif',
      headingFont: '"Space Grotesk", Impact, "Arial Black", sans-serif',
      category: 'sans-serif',
    },
    tags: ['brutalist', 'bold', 'high-contrast', 'raw', 'dramatic', 'yellow'],
  },
  {
    name: 'cyberpunk',
    label: 'Cyberpunk',
    style: 'bold',
    mood: 'dramatic',
    description: 'Neon pink and cyan on light background',
    colors: {
      background: '260 30% 98%',
      foreground: '260 50% 12%',
      card: '260 35% 96%',
      cardForeground: '260 50% 12%',
      primary: '320 90% 55%',
      primaryForeground: '0 0% 100%',
      secondary: '260 25% 92%',
      secondaryForeground: '260 50% 18%',
      muted: '260 20% 94%',
      mutedForeground: '260 40% 45%',
      accent: '180 90% 45%',
      accentForeground: '260 30% 98%',
      border: '260 25% 88%',
      ring: '320 90% 55%',
    },
    typography: {
      fontFamily: '"Share Tech Mono", "Fira Code", "Roboto Mono", monospace',
      headingFont: '"Rajdhani", "Audiowide", "Impact", sans-serif',
      category: 'monospace',
    },
    tags: ['neon', 'futuristic', 'pink', 'cyan', 'sci-fi', 'gaming'],
  },
  {
    name: 'retro-arcade',
    label: 'Retro Arcade',
    style: 'retro',
    mood: 'energetic',
    description: '80s arcade aesthetic with pixel fonts',
    colors: {
      background: '240 25% 98%',
      foreground: '240 50% 12%',
      card: '240 30% 96%',
      cardForeground: '240 50% 12%',
      primary: '120 90% 45%',
      primaryForeground: '240 25% 98%',
      secondary: '240 20% 92%',
      secondaryForeground: '240 50% 18%',
      muted: '240 15% 94%',
      mutedForeground: '240 40% 45%',
      accent: '0 90% 50%',
      accentForeground: '0 0% 100%',
      border: '240 20% 88%',
      ring: '120 90% 45%',
    },
    typography: {
      fontFamily: '"Press Start 2P", "VT323", "Courier New", monospace',
      headingFont: '"Press Start 2P", "VT323", "Courier New", monospace',
      category: 'monospace',
    },
    tags: ['retro', '80s', 'arcade', 'pixel', 'gaming', 'nostalgic', 'green'],
  },

  // Soft/Pastel Themes
  {
    name: 'pastel-dreams',
    label: 'Pastel Dreams',
    style: 'playful',
    mood: 'calm',
    description: 'Soft lavender and pink pastels',
    colors: {
      background: '300 30% 98%',
      foreground: '280 20% 20%',
      card: '300 40% 95%',
      cardForeground: '280 20% 20%',
      primary: '280 60% 70%',
      primaryForeground: '280 20% 15%',
      secondary: '200 50% 90%',
      secondaryForeground: '280 20% 25%',
      muted: '300 25% 92%',
      mutedForeground: '280 15% 45%',
      accent: '340 60% 75%',
      accentForeground: '280 20% 15%',
      border: '300 30% 85%',
      ring: '280 60% 70%',
    },
    typography: {
      fontFamily: '"Quicksand", "Comfortaa", system-ui, sans-serif',
      headingFont: '"Quicksand", "Comfortaa", system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['pastel', 'soft', 'lavender', 'pink', 'dreamy', 'gentle'],
  },
  {
    name: 'candyland',
    label: 'Candyland',
    style: 'playful',
    mood: 'energetic',
    description: 'Bright playful colors for fun interfaces',
    colors: {
      background: '330 50% 97%',
      foreground: '330 60% 15%',
      card: '330 60% 94%',
      cardForeground: '330 60% 15%',
      primary: '330 90% 60%',
      primaryForeground: '0 0% 100%',
      secondary: '180 60% 85%',
      secondaryForeground: '330 60% 20%',
      muted: '330 40% 90%',
      mutedForeground: '330 40% 40%',
      accent: '50 100% 55%',
      accentForeground: '330 60% 15%',
      border: '330 50% 82%',
      ring: '330 90% 60%',
    },
    typography: {
      fontFamily: '"Baloo 2", "Comic Neue", "Comic Sans MS", cursive',
      headingFont: '"Baloo 2", "Fredoka One", "Comic Sans MS", cursive',
      category: 'cursive',
    },
    tags: ['playful', 'candy', 'bright', 'fun', 'kids', 'colorful', 'pink'],
  },
  {
    name: 'soft-pop',
    label: 'Soft Pop',
    style: 'playful',
    mood: 'energetic',
    description: 'Vibrant and playful with bold accents',
    colors: {
      background: '80 33% 96%',
      foreground: '0 0% 0%',
      card: '0 0% 100%',
      cardForeground: '0 0% 0%',
      primary: '243 75% 59%',
      primaryForeground: '0 0% 100%',
      secondary: '170 70% 50%',
      secondaryForeground: '0 0% 100%',
      muted: '0 0% 94%',
      mutedForeground: '0 0% 20%',
      accent: '38 92% 50%',
      accentForeground: '0 0% 0%',
      border: '0 0% 0%',
      ring: '250 60% 75%',
    },
    typography: {
      fontFamily: '"DM Sans", system-ui, sans-serif',
      headingFont: '"DM Sans", system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['pop', 'vibrant', 'colorful', 'bold', 'modern', 'energetic'],
  },

  // Tech/Developer Themes
  {
    name: 'bold-tech',
    label: 'Bold Tech',
    style: 'tech',
    mood: 'tech',
    description: 'Strong tech-forward with blue and teal',
    colors: {
      background: '220 20% 98%',
      foreground: '220 40% 12%',
      card: '220 25% 96%',
      cardForeground: '220 40% 12%',
      primary: '200 90% 50%',
      primaryForeground: '220 20% 98%',
      secondary: '220 15% 92%',
      secondaryForeground: '220 40% 18%',
      muted: '220 12% 94%',
      mutedForeground: '220 30% 45%',
      accent: '160 90% 40%',
      accentForeground: '220 20% 98%',
      border: '220 15% 88%',
      ring: '200 90% 50%',
    },
    typography: {
      fontFamily: '"JetBrains Mono", "Fira Code", "Source Code Pro", monospace',
      headingFont: '"Inter", "SF Pro Display", system-ui, sans-serif',
      category: 'monospace',
    },
    tags: ['tech', 'developer', 'blue', 'teal', 'monospace', 'modern'],
  },
  {
    name: 'utilitarian',
    label: 'Utilitarian',
    style: 'tech',
    mood: 'professional',
    description: 'Tactical briefing document aesthetic',
    colors: {
      background: '45 30% 92%',
      foreground: '0 0% 0%',
      card: '45 35% 95%',
      cardForeground: '0 0% 0%',
      primary: '15 85% 55%',
      primaryForeground: '0 0% 100%',
      secondary: '45 20% 85%',
      secondaryForeground: '0 0% 0%',
      muted: '45 15% 88%',
      mutedForeground: '0 0% 35%',
      accent: '15 85% 55%',
      accentForeground: '0 0% 100%',
      border: '0 0% 0%',
      ring: '15 85% 55%',
    },
    typography: {
      fontFamily: '"SF Mono", "Fira Code", "Fira Mono", Menlo, Consolas, monospace',
      headingFont: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      category: 'monospace',
    },
    tags: ['tactical', 'military', 'document', 'briefing', 'monospace', 'orange'],
  },

  // Cosmic/Space Themes
  {
    name: 'cosmic-night',
    label: 'Cosmic Night',
    style: 'bold',
    mood: 'dramatic',
    description: 'Deep space purple with cyan accents',
    colors: {
      background: '260 30% 98%',
      foreground: '260 40% 12%',
      card: '260 35% 96%',
      cardForeground: '260 40% 12%',
      primary: '280 70% 55%',
      primaryForeground: '0 0% 100%',
      secondary: '260 25% 92%',
      secondaryForeground: '260 40% 18%',
      muted: '260 20% 94%',
      mutedForeground: '260 30% 45%',
      accent: '200 90% 50%',
      accentForeground: '0 0% 100%',
      border: '260 25% 88%',
      ring: '280 70% 55%',
    },
    typography: {
      fontFamily: '"Orbitron", "Exo 2", system-ui, sans-serif',
      headingFont: '"Orbitron", "Exo 2", system-ui, sans-serif',
      category: 'display',
    },
    tags: ['space', 'cosmic', 'purple', 'cyan', 'futuristic', 'night'],
  },
  {
    name: 'northern-lights',
    label: 'Northern Lights',
    style: 'bold',
    mood: 'cool',
    description: 'Aurora borealis inspired teal and purple',
    colors: {
      background: '220 25% 98%',
      foreground: '180 40% 12%',
      card: '220 30% 96%',
      cardForeground: '180 40% 12%',
      primary: '160 70% 45%',
      primaryForeground: '220 25% 98%',
      secondary: '220 20% 92%',
      secondaryForeground: '180 40% 18%',
      muted: '220 15% 94%',
      mutedForeground: '180 30% 45%',
      accent: '280 65% 55%',
      accentForeground: '0 0% 100%',
      border: '220 20% 88%',
      ring: '160 70% 45%',
    },
    typography: {
      fontFamily: '"Outfit", "Montserrat", system-ui, sans-serif',
      headingFont: '"Outfit", "Montserrat", system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['aurora', 'teal', 'purple', 'nature', 'cool', 'magical'],
  },
  {
    name: 'starry-night',
    label: 'Starry Night',
    style: 'elegant',
    mood: 'dramatic',
    description: 'Van Gogh inspired deep blue with gold stars',
    colors: {
      background: '216 33% 97%',
      foreground: '224 37% 16%',
      card: '216 30% 89%',
      cardForeground: '224 37% 16%',
      primary: '221 47% 43%',
      primaryForeground: '48 100% 95%',
      secondary: '48 70% 85%',
      secondaryForeground: '224 37% 16%',
      muted: '60 10% 88%',
      mutedForeground: '221 47% 43%',
      accent: '200 50% 60%',
      accentForeground: '48 100% 95%',
      border: '216 25% 75%',
      ring: '48 70% 85%',
    },
    typography: {
      fontFamily: '"Libre Baskerville", Georgia, serif',
      headingFont: '"Libre Baskerville", Georgia, serif',
      category: 'serif',
    },
    tags: ['artistic', 'blue', 'gold', 'night', 'van-gogh', 'stars'],
  },

  // Warm/Cozy Themes
  {
    name: 'caffeine',
    label: 'Caffeine',
    style: 'nature',
    mood: 'warm',
    description: 'Coffee shop browns and cream',
    colors: {
      background: '30 15% 95%',
      foreground: '25 40% 12%',
      card: '30 20% 90%',
      cardForeground: '25 40% 12%',
      primary: '25 70% 30%',
      primaryForeground: '30 15% 95%',
      secondary: '30 15% 82%',
      secondaryForeground: '25 40% 18%',
      muted: '30 12% 85%',
      mutedForeground: '25 25% 40%',
      accent: '15 80% 45%',
      accentForeground: '0 0% 100%',
      border: '30 15% 75%',
      ring: '25 70% 30%',
    },
    typography: {
      fontFamily: '"Libre Baskerville", "Georgia", serif',
      headingFont: '"Libre Baskerville", "Georgia", serif',
      category: 'serif',
    },
    tags: ['coffee', 'brown', 'warm', 'cozy', 'cafe', 'organic'],
  },
  {
    name: 'mocha-mousse',
    label: 'Mocha Mousse',
    style: 'nature',
    mood: 'warm',
    description: 'Coffee browns and creams - Pantone 2025 inspired',
    colors: {
      background: '55 30% 92%',
      foreground: '16 15% 29%',
      card: '55 30% 92%',
      cardForeground: '16 15% 29%',
      primary: '18 26% 52%',
      primaryForeground: '0 0% 100%',
      secondary: '30 25% 70%',
      secondaryForeground: '0 0% 100%',
      muted: '20 30% 80%',
      mutedForeground: '20 25% 40%',
      accent: '20 30% 80%',
      accentForeground: '16 15% 29%',
      border: '30 25% 70%',
      ring: '18 26% 52%',
    },
    typography: {
      fontFamily: '"DM Sans", system-ui, sans-serif',
      headingFont: '"DM Sans", system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['pantone', 'mocha', 'brown', 'cream', 'warm', '2025'],
  },
  {
    name: 'sunset-horizon',
    label: 'Sunset Horizon',
    style: 'bold',
    mood: 'warm',
    description: 'Warm sunset gradients with orange and pink',
    colors: {
      background: '25 40% 96%',
      foreground: '15 50% 12%',
      card: '25 45% 92%',
      cardForeground: '15 50% 12%',
      primary: '15 90% 55%',
      primaryForeground: '0 0% 100%',
      secondary: '35 35% 85%',
      secondaryForeground: '15 50% 18%',
      muted: '30 30% 88%',
      mutedForeground: '15 30% 42%',
      accent: '340 85% 60%',
      accentForeground: '0 0% 100%',
      border: '25 35% 78%',
      ring: '15 90% 55%',
    },
    typography: {
      fontFamily: '"Rubik", "Nunito", system-ui, sans-serif',
      headingFont: '"Rubik", "Nunito", system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['sunset', 'orange', 'pink', 'warm', 'gradient', 'vibrant'],
  },

  // Minimal/Clean Themes
  {
    name: 'modern-minimal',
    label: 'Modern Minimal',
    style: 'minimal',
    mood: 'professional',
    description: 'Ultra clean black and white',
    colors: {
      background: '0 0% 100%',
      foreground: '0 0% 5%',
      card: '0 0% 98%',
      cardForeground: '0 0% 5%',
      primary: '0 0% 5%',
      primaryForeground: '0 0% 100%',
      secondary: '0 0% 95%',
      secondaryForeground: '0 0% 10%',
      muted: '0 0% 96%',
      mutedForeground: '0 0% 40%',
      accent: '0 0% 15%',
      accentForeground: '0 0% 100%',
      border: '0 0% 90%',
      ring: '0 0% 5%',
    },
    typography: {
      fontFamily: '"Manrope", "Helvetica Neue", Helvetica, Arial, sans-serif',
      headingFont: '"Manrope", "Helvetica Neue", Helvetica, Arial, sans-serif',
      category: 'sans-serif',
    },
    tags: ['minimal', 'clean', 'monochrome', 'modern', 'simple', 'white'],
  },
  {
    name: 'clean-slate',
    label: 'Clean Slate',
    style: 'minimal',
    mood: 'professional',
    description: 'Minimal gray with blue accent',
    colors: {
      background: '210 15% 98%',
      foreground: '210 20% 15%',
      card: '210 15% 95%',
      cardForeground: '210 20% 15%',
      primary: '210 100% 50%',
      primaryForeground: '0 0% 100%',
      secondary: '210 10% 90%',
      secondaryForeground: '210 20% 20%',
      muted: '210 10% 92%',
      mutedForeground: '210 10% 45%',
      accent: '210 90% 55%',
      accentForeground: '0 0% 100%',
      border: '210 15% 85%',
      ring: '210 100% 50%',
    },
    typography: {
      fontFamily: '"DM Sans", "Roboto", system-ui, sans-serif',
      headingFont: '"DM Sans", "Roboto", system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['minimal', 'gray', 'blue', 'clean', 'slate', 'professional'],
  },
  {
    name: 'base',
    label: 'Default',
    style: 'minimal',
    mood: 'professional',
    description: 'Default shadcn/ui theme',
    colors: {
      background: '0 0% 100%',
      foreground: '222.2 84% 4.9%',
      card: '0 0% 100%',
      cardForeground: '222.2 84% 4.9%',
      primary: '222.2 47.4% 11.2%',
      primaryForeground: '210 40% 98%',
      secondary: '210 40% 96.1%',
      secondaryForeground: '222.2 47.4% 11.2%',
      muted: '210 40% 96.1%',
      mutedForeground: '215.4 16.3% 46.9%',
      accent: '210 40% 96.1%',
      accentForeground: '222.2 47.4% 11.2%',
      border: '214.3 31.8% 91.4%',
      ring: '222.2 84% 4.9%',
    },
    typography: {
      fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
      headingFont: 'Inter, system-ui, -apple-system, sans-serif',
      category: 'sans-serif',
    },
    tags: ['default', 'shadcn', 'neutral', 'base', 'standard'],
  },

  // Pink/Rose Themes
  {
    name: 'quantum-rose',
    label: 'Quantum Rose',
    style: 'elegant',
    mood: 'warm',
    description: 'Soft pink and rose tones',
    colors: {
      background: '350 30% 97%',
      foreground: '350 40% 15%',
      card: '350 35% 94%',
      cardForeground: '350 40% 15%',
      primary: '350 80% 60%',
      primaryForeground: '0 0% 100%',
      secondary: '350 25% 88%',
      secondaryForeground: '350 40% 20%',
      muted: '350 20% 90%',
      mutedForeground: '350 20% 45%',
      accent: '320 70% 55%',
      accentForeground: '0 0% 100%',
      border: '350 25% 82%',
      ring: '350 80% 60%',
    },
    typography: {
      fontFamily: '"Raleway", "Lato", system-ui, sans-serif',
      headingFont: '"Raleway", "Lato", system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['pink', 'rose', 'soft', 'feminine', 'elegant', 'romantic'],
  },
  {
    name: 'midnight-bloom',
    label: 'Midnight Bloom',
    style: 'elegant',
    mood: 'dramatic',
    description: 'Purple with magenta accents',
    colors: {
      background: '270 25% 98%',
      foreground: '270 40% 12%',
      card: '270 30% 96%',
      cardForeground: '270 40% 12%',
      primary: '300 65% 55%',
      primaryForeground: '0 0% 100%',
      secondary: '270 20% 92%',
      secondaryForeground: '270 40% 18%',
      muted: '270 15% 94%',
      mutedForeground: '270 30% 45%',
      accent: '330 75% 60%',
      accentForeground: '0 0% 100%',
      border: '270 20% 88%',
      ring: '300 65% 55%',
    },
    typography: {
      fontFamily: '"Crimson Text", "Crimson Pro", Georgia, serif',
      headingFont: '"Crimson Text", "Crimson Pro", Georgia, serif',
      category: 'serif',
    },
    tags: ['purple', 'magenta', 'bloom', 'floral', 'elegant', 'night'],
  },

  // Purple/Violet Themes
  {
    name: 'violet-bloom',
    label: 'Violet Bloom',
    style: 'elegant',
    mood: 'creative',
    description: 'Purple elegance with vibrant violet primary',
    colors: {
      background: '0 0% 99%',
      foreground: '0 0% 0%',
      card: '0 0% 99%',
      cardForeground: '0 0% 0%',
      primary: '258 100% 60%',
      primaryForeground: '0 0% 100%',
      secondary: '220 20% 93%',
      secondaryForeground: '0 0% 3%',
      muted: '0 0% 96%',
      mutedForeground: '0 0% 32%',
      accent: '220 100% 95%',
      accentForeground: '220 90% 45%',
      border: '270 15% 91%',
      ring: '0 0% 0%',
    },
    typography: {
      fontFamily: '"Plus Jakarta Sans", system-ui, sans-serif',
      headingFont: '"Plus Jakarta Sans", system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['violet', 'purple', 'elegant', 'modern', 'creative', 'vibrant'],
  },
  {
    name: 'amethyst-haze',
    label: 'Amethyst Haze',
    style: 'elegant',
    mood: 'calm',
    description: 'Soft purple mist aesthetic',
    colors: {
      background: '260 23% 97%',
      foreground: '243 14% 27%',
      card: '0 0% 100%',
      cardForeground: '243 14% 27%',
      primary: '260 23% 57%',
      primaryForeground: '260 23% 97%',
      secondary: '260 25% 88%',
      secondaryForeground: '243 14% 27%',
      muted: '260 20% 86%',
      mutedForeground: '260 25% 45%',
      accent: '340 50% 80%',
      accentForeground: '20 50% 20%',
      border: '260 20% 82%',
      ring: '260 23% 57%',
    },
    typography: {
      fontFamily: '"Geist", system-ui, sans-serif',
      headingFont: '"Geist", system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['amethyst', 'purple', 'haze', 'soft', 'dreamy', 'calm'],
  },

  // Ocean/Blue Themes
  {
    name: 'ocean-breeze',
    label: 'Ocean Breeze',
    style: 'nature',
    mood: 'cool',
    description: 'Cool ocean blues with teal accent',
    colors: {
      background: '200 30% 97%',
      foreground: '200 40% 12%',
      card: '200 35% 93%',
      cardForeground: '200 40% 12%',
      primary: '200 90% 45%',
      primaryForeground: '0 0% 100%',
      secondary: '200 25% 85%',
      secondaryForeground: '200 40% 18%',
      muted: '200 20% 88%',
      mutedForeground: '200 20% 42%',
      accent: '180 70% 45%',
      accentForeground: '0 0% 100%',
      border: '200 25% 78%',
      ring: '200 90% 45%',
    },
    typography: {
      fontFamily: '"Source Sans Pro", "Open Sans", system-ui, sans-serif',
      headingFont: '"Source Sans Pro", "Open Sans", system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['ocean', 'blue', 'teal', 'water', 'cool', 'refreshing'],
  },

  // Gaming Themes
  {
    name: 'doom-64',
    label: 'Doom 64',
    style: 'retro',
    mood: 'dramatic',
    description: 'Retro game aesthetic with red and olive',
    colors: {
      background: '0 0% 80%',
      foreground: '0 0% 12%',
      card: '0 0% 69%',
      cardForeground: '0 0% 12%',
      primary: '0 73% 41%',
      primaryForeground: '0 0% 100%',
      secondary: '80 40% 35%',
      secondaryForeground: '0 0% 100%',
      muted: '0 0% 72%',
      mutedForeground: '0 0% 29%',
      accent: '210 50% 50%',
      accentForeground: '0 0% 100%',
      border: '0 0% 31%',
      ring: '0 73% 41%',
    },
    typography: {
      fontFamily: '"Oxanium", system-ui, sans-serif',
      headingFont: '"Oxanium", system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['gaming', 'retro', 'doom', 'red', 'olive', '90s', 'shooter'],
  },

  // Research/Academic Themes
  {
    name: 'research',
    label: 'Research',
    style: 'elegant',
    mood: 'professional',
    description: 'Clean academic paper aesthetic',
    colors: {
      background: '0 0% 100%',
      foreground: '0 0% 8%',
      card: '0 0% 99%',
      cardForeground: '0 0% 8%',
      primary: '220 60% 45%',
      primaryForeground: '0 0% 100%',
      secondary: '0 0% 97%',
      secondaryForeground: '0 0% 15%',
      muted: '0 0% 96%',
      mutedForeground: '0 0% 40%',
      accent: '220 50% 95%',
      accentForeground: '220 60% 35%',
      border: '0 0% 88%',
      ring: '220 60% 45%',
    },
    typography: {
      fontFamily: '"Source Serif Pro", "Crimson Pro", Georgia, serif',
      headingFont: '"Crimson Pro", "Source Serif Pro", Georgia, serif',
      category: 'serif',
    },
    tags: ['academic', 'research', 'paper', 'scholarly', 'serif', 'blue'],
  },

  // Warm/Amber Themes
  {
    name: 'amber-minimal',
    label: 'Amber Minimal',
    style: 'minimal',
    mood: 'warm',
    description: 'Clean white with warm amber accent',
    colors: {
      background: '0 0% 100%',
      foreground: '0 0% 15%',
      card: '0 0% 100%',
      cardForeground: '0 0% 15%',
      primary: '38 92% 50%',
      primaryForeground: '0 0% 0%',
      secondary: '220 15% 95%',
      secondaryForeground: '0 0% 29%',
      muted: '220 15% 98%',
      mutedForeground: '0 0% 44%',
      accent: '48 100% 96%',
      accentForeground: '38 80% 30%',
      border: '220 13% 90%',
      ring: '38 92% 50%',
    },
    typography: {
      fontFamily: '"Inter", system-ui, sans-serif',
      headingFont: '"Inter", system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['amber', 'minimal', 'warm', 'gold', 'clean', 'modern'],
  },
  {
    name: 'solar-dusk',
    label: 'Solar Dusk',
    style: 'bold',
    mood: 'warm',
    description: 'Warm sunset tones with burnt orange',
    colors: {
      background: '40 60% 98%',
      foreground: '21 18% 25%',
      card: '40 35% 97%',
      cardForeground: '21 18% 25%',
      primary: '26 90% 37%',
      primaryForeground: '0 0% 100%',
      secondary: '38 50% 75%',
      secondaryForeground: '21 15% 30%',
      muted: '40 30% 92%',
      mutedForeground: '21 12% 45%',
      accent: '40 50% 85%',
      accentForeground: '21 15% 30%',
      border: '40 40% 82%',
      ring: '26 90% 37%',
    },
    typography: {
      fontFamily: '"Oxanium", system-ui, sans-serif',
      headingFont: '"Oxanium", system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['solar', 'dusk', 'orange', 'warm', 'sunset', 'desert'],
  },

  // Morphism Themes
  {
    name: 'claymorphism',
    label: 'Claymorphism',
    style: 'playful',
    mood: 'creative',
    description: 'Soft shadows, rounded, clay-like 3D effect',
    colors: {
      background: '220 20% 97%',
      foreground: '220 30% 15%',
      card: '220 25% 94%',
      cardForeground: '220 30% 15%',
      primary: '220 80% 55%',
      primaryForeground: '0 0% 100%',
      secondary: '220 20% 88%',
      secondaryForeground: '220 30% 20%',
      muted: '220 15% 90%',
      mutedForeground: '220 15% 45%',
      accent: '260 70% 60%',
      accentForeground: '0 0% 100%',
      border: '220 20% 85%',
      ring: '220 80% 55%',
    },
    typography: {
      fontFamily: '"Poppins", "Nunito Sans", system-ui, sans-serif',
      headingFont: '"Poppins", "Nunito Sans", system-ui, sans-serif',
      category: 'sans-serif',
    },
    tags: ['clay', '3d', 'soft', 'rounded', 'modern', 'playful', 'blue'],
  },

  // Chat/Social Themes
  {
    name: 't3-chat',
    label: 'T3 Chat',
    style: 'playful',
    mood: 'creative',
    description: 'Pink/purple chat interface inspired by T3',
    colors: {
      background: '300 33% 97%',
      foreground: '296 56% 21%',
      card: '300 33% 97%',
      cardForeground: '296 56% 21%',
      primary: '333 43% 46%',
      primaryForeground: '0 0% 100%',
      secondary: '320 50% 94%',
      secondaryForeground: '300 40% 45%',
      muted: '300 40% 96%',
      mutedForeground: '300 30% 50%',
      accent: '320 50% 94%',
      accentForeground: '300 40% 45%',
      border: '300 40% 92%',
      ring: '330 70% 50%',
    },
    typography: {
      fontFamily: 'system-ui, -apple-system, sans-serif',
      headingFont: 'system-ui, -apple-system, sans-serif',
      category: 'sans-serif',
    },
    tags: ['chat', 'pink', 'purple', 'social', 'messaging', 't3'],
  },

  // Sportswear/Lifestyle Brands
  {
    name: 'nike',
    label: 'Nike',
    style: 'bold',
    mood: 'energetic',
    description: 'Nike - Bold athletic design with warm off-white and Futura-inspired type',
    colors: {
      background: '40 30% 95%',
      foreground: '0 0% 8%',
      card: '40 35% 97%',
      cardForeground: '0 0% 8%',
      primary: '0 0% 8%',
      primaryForeground: '40 30% 97%',
      secondary: '40 20% 90%',
      secondaryForeground: '0 0% 15%',
      muted: '40 15% 88%',
      mutedForeground: '0 0% 45%',
      accent: '28 100% 55%',
      accentForeground: '0 0% 100%',
      border: '40 20% 85%',
      ring: '0 0% 8%',
    },
    typography: {
      fontFamily: '"Helvetica Neue", -apple-system, BlinkMacSystemFont, Arial, sans-serif',
      headingFont: '"Helvetica Neue", -apple-system, BlinkMacSystemFont, Arial, sans-serif',
      category: 'sans-serif',
    },
    tags: ['brand', 'athletic', 'bold', 'sport', 'nike', 'swoosh', 'orange'],
  },
  {
    name: 'adidas',
    label: 'Adidas',
    style: 'bold',
    mood: 'energetic',
    description: 'Adidas - Clean sportswear aesthetic with strong blue accent',
    colors: {
      background: '0 0% 98%',
      foreground: '0 0% 8%',
      card: '0 0% 100%',
      cardForeground: '0 0% 8%',
      primary: '210 100% 45%',
      primaryForeground: '0 0% 100%',
      secondary: '0 0% 94%',
      secondaryForeground: '0 0% 15%',
      muted: '0 0% 92%',
      mutedForeground: '0 0% 50%',
      accent: '0 0% 8%',
      accentForeground: '0 0% 100%',
      border: '0 0% 88%',
      ring: '210 100% 45%',
    },
    typography: {
      fontFamily: '"Helvetica Neue", -apple-system, BlinkMacSystemFont, Arial, sans-serif',
      headingFont: '"Helvetica Neue", -apple-system, BlinkMacSystemFont, Arial, sans-serif',
      category: 'sans-serif',
    },
    tags: ['brand', 'athletic', 'sport', 'adidas', 'blue', 'clean'],
  },

  // Stationery/Knowledge Themes
  {
    name: 'notebook',
    label: 'Notebook',
    style: 'retro',
    mood: 'warm',
    description: 'Notebook - Handwritten journal feel with warm parchment tones and serif headings',
    colors: {
      background: '40 30% 92%',
      foreground: '0 0% 20%',
      card: '0 0% 100%',
      cardForeground: '0 0% 20%',
      primary: '38 70% 50%',
      primaryForeground: '0 0% 100%',
      secondary: '40 20% 88%',
      secondaryForeground: '0 0% 20%',
      muted: '40 15% 94%',
      mutedForeground: '0 0% 40%',
      accent: '38 50% 85%',
      accentForeground: '0 0% 20%',
      border: '40 20% 80%',
      ring: '38 70% 50%',
    },
    typography: {
      fontFamily: '"Courier Prime", "Courier New", Courier, monospace',
      headingFont: '"Libre Baskerville", Georgia, serif',
      category: 'monospace',
    },
    tags: ['notebook', 'journal', 'handwritten', 'warm', 'paper', 'stationery'],
  },
  {
    name: 'field-guide',
    label: 'Field Guide',
    style: 'retro',
    mood: 'warm',
    description: 'Field Guide - Naturalist reference book with warm cream and red accents',
    colors: {
      background: '45 35% 94%',
      foreground: '0 0% 15%',
      card: '45 40% 96%',
      cardForeground: '0 0% 15%',
      primary: '355 78% 50%',
      primaryForeground: '45 35% 96%',
      secondary: '45 25% 88%',
      secondaryForeground: '0 0% 20%',
      muted: '45 20% 90%',
      mutedForeground: '0 0% 40%',
      accent: '355 78% 50%',
      accentForeground: '45 35% 96%',
      border: '355 78% 50%',
      ring: '355 78% 50%',
    },
    typography: {
      fontFamily: '"DM Sans", "Inter", ui-sans-serif, system-ui, sans-serif',
      headingFont: '"Fraunces", "Playfair Display", Georgia, serif',
      category: 'sans-serif',
    },
    tags: ['field-guide', 'nature', 'reference', 'warm', 'red', 'cream', 'botanical'],
  },

  // Eastern/Philosophical Themes
  {
    name: 'tao',
    label: 'Tao',
    style: 'elegant',
    mood: 'calm',
    description: 'Tao - Serene philosophical aesthetic with cool blue tones and serif type',
    colors: {
      background: '220 15% 96%',
      foreground: '220 25% 18%',
      card: '220 20% 92%',
      cardForeground: '220 25% 18%',
      primary: '210 60% 50%',
      primaryForeground: '0 0% 100%',
      secondary: '220 12% 88%',
      secondaryForeground: '220 25% 22%',
      muted: '220 10% 90%',
      mutedForeground: '220 15% 45%',
      accent: '200 45% 55%',
      accentForeground: '0 0% 100%',
      border: '220 15% 82%',
      ring: '210 60% 50%',
    },
    typography: {
      fontFamily: '"Crimson Text", "EB Garamond", Georgia, serif',
      headingFont: '"Crimson Text", "EB Garamond", Georgia, serif',
      category: 'serif',
    },
    tags: ['zen', 'philosophy', 'calm', 'blue', 'serif', 'spiritual', 'minimal'],
  },

  // Fabric/Lifestyle Themes
  {
    name: 'denim',
    label: 'Denim',
    style: 'bold',
    mood: 'cool',
    description: 'Denim - Rich indigo blue fabric aesthetic with elegant serif headings',
    colors: {
      background: '225 30% 97%',
      foreground: '228 45% 18%',
      card: '225 35% 94%',
      cardForeground: '228 45% 18%',
      primary: '228 65% 42%',
      primaryForeground: '45 30% 96%',
      secondary: '225 25% 88%',
      secondaryForeground: '228 45% 22%',
      muted: '225 20% 91%',
      mutedForeground: '228 30% 45%',
      accent: '225 55% 52%',
      accentForeground: '45 30% 96%',
      border: '225 25% 82%',
      ring: '228 65% 42%',
    },
    typography: {
      fontFamily: '"DM Sans", "Inter", ui-sans-serif, system-ui, sans-serif',
      headingFont: '"Playfair Display", "Cormorant Garamond", Georgia, serif',
      category: 'sans-serif',
    },
    tags: ['denim', 'blue', 'fabric', 'indigo', 'fashion', 'serif'],
  },

  // Editorial/Typography-First Themes
  {
    name: 'kinetic-editorial',
    label: 'Kinetic Editorial',
    style: 'elegant',
    mood: 'dramatic',
    description: 'Kinetic Editorial - High-contrast monochrome with bold Swiss-style typography',
    colors: {
      background: '0 0% 99%',
      foreground: '0 0% 4%',
      card: '0 0% 100%',
      cardForeground: '0 0% 4%',
      primary: '0 0% 4%',
      primaryForeground: '0 0% 100%',
      secondary: '0 0% 96%',
      secondaryForeground: '0 0% 8%',
      muted: '0 0% 94%',
      mutedForeground: '0 0% 40%',
      accent: '0 0% 4%',
      accentForeground: '0 0% 100%',
      border: '0 0% 88%',
      ring: '0 0% 4%',
    },
    typography: {
      fontFamily: '"Neue Haas Grotesk Display Pro", "Helvetica Neue", -apple-system, sans-serif',
      headingFont: '"Neue Haas Grotesk Display Pro", "Helvetica Neue", -apple-system, sans-serif',
      category: 'sans-serif',
    },
    tags: ['editorial', 'monochrome', 'swiss', 'typography', 'kinetic', 'bold', 'black-white'],
  },

  // Hardware/Product Design Themes
  {
    name: 'teenage-engineering',
    label: 'Teenage Engineering',
    style: 'retro',
    mood: 'creative',
    description: 'Teenage Engineering - Industrial product design with orange and monospace type',
    colors: {
      background: '0 0% 90%',
      foreground: '0 0% 17%',
      card: '0 0% 94%',
      cardForeground: '0 0% 17%',
      primary: '14 100% 57%',
      primaryForeground: '0 0% 100%',
      secondary: '0 0% 78%',
      secondaryForeground: '0 0% 17%',
      muted: '0 0% 85%',
      mutedForeground: '0 0% 40%',
      accent: '14 100% 57%',
      accentForeground: '0 0% 100%',
      border: '0 0% 17%',
      ring: '14 100% 57%',
    },
    typography: {
      fontFamily: '"SF Mono", "Roboto Mono", "Courier New", monospace',
      headingFont: '"SF Mono", "Roboto Mono", "Courier New", monospace',
      category: 'monospace',
    },
    tags: ['hardware', 'product', 'orange', 'industrial', 'monospace', 'creative', 'teenage-engineering'],
  },

  // Fintech/Startup Themes
  {
    name: 'fynt',
    label: 'Fynt',
    style: 'tech',
    mood: 'dramatic',
    description: 'Fynt - Dark fintech aesthetic with warm orange accent and serif headings',
    colors: {
      background: '0 0% 8%',
      foreground: '0 0% 100%',
      card: '0 0% 10%',
      cardForeground: '0 0% 100%',
      primary: '14 88% 54%',
      primaryForeground: '0 0% 100%',
      secondary: '0 0% 12%',
      secondaryForeground: '0 0% 100%',
      muted: '0 0% 14%',
      mutedForeground: '240 1% 50%',
      accent: '14 88% 54%',
      accentForeground: '0 0% 100%',
      border: '0 0% 20%',
      ring: '14 88% 54%',
    },
    typography: {
      fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
      headingFont: 'Georgia, "Times New Roman", serif',
      category: 'sans-serif',
    },
    tags: ['fintech', 'dark', 'orange', 'startup', 'finance', 'serif-heading'],
  },

  // Science/Quantum Themes
  {
    name: 'entangled-photons',
    label: 'Entangled Photons',
    style: 'tech',
    mood: 'cool',
    description: 'Entangled Photons - Quantum physics inspired with cyan and purple accents',
    colors: {
      background: '220 25% 96%',
      foreground: '210 50% 10%',
      card: '215 30% 93%',
      cardForeground: '210 50% 10%',
      primary: '185 90% 45%',
      primaryForeground: '210 60% 5%',
      secondary: '260 40% 92%',
      secondaryForeground: '260 30% 20%',
      muted: '215 20% 90%',
      mutedForeground: '210 20% 45%',
      accent: '280 70% 60%',
      accentForeground: '0 0% 100%',
      border: '215 25% 85%',
      ring: '185 90% 45%',
    },
    typography: {
      fontFamily: '"IBM Plex Sans", "Inter", system-ui, -apple-system, sans-serif',
      headingFont: '"IBM Plex Mono", "JetBrains Mono", monospace',
      category: 'sans-serif',
    },
    tags: ['quantum', 'science', 'cyan', 'purple', 'physics', 'tech', 'cool'],
  },

  // Developer/Sandbox Themes
  {
    name: 'e2b',
    label: 'E2B',
    style: 'tech',
    mood: 'dramatic',
    description: 'E2B - Dark developer sandbox with gold accent and monospace headings',
    colors: {
      background: '240 6% 6%',
      foreground: '0 0% 92%',
      card: '240 5% 10%',
      cardForeground: '0 0% 92%',
      primary: '38 91% 59%',
      primaryForeground: '240 6% 6%',
      secondary: '240 4% 14%',
      secondaryForeground: '0 0% 85%',
      muted: '240 4% 18%',
      mutedForeground: '0 0% 55%',
      accent: '38 91% 59%',
      accentForeground: '240 6% 6%',
      border: '240 4% 22%',
      ring: '38 91% 59%',
    },
    typography: {
      fontFamily: '"IBM Plex Sans", system-ui, -apple-system, sans-serif',
      headingFont: '"IBM Plex Mono", "JetBrains Mono", monospace',
      category: 'sans-serif',
    },
    tags: ['developer', 'sandbox', 'dark', 'gold', 'terminal', 'e2b', 'code'],
  },
];

/**
 * Get all extracted themes
 */
export function getAllThemes(): ExtractedTheme[] {
  return EXTRACTED_THEMES;
}

/**
 * Get theme by name
 */
export function getThemeByName(name: string): ExtractedTheme | undefined {
  return EXTRACTED_THEMES.find((t) => t.name === name);
}

/**
 * Filter themes by style
 */
export function filterByStyle(style: DesignStyle): ExtractedTheme[] {
  return EXTRACTED_THEMES.filter((t) => t.style === style);
}

/**
 * Filter themes by mood
 */
export function filterByMood(mood: DesignMood): ExtractedTheme[] {
  return EXTRACTED_THEMES.filter((t) => t.mood === mood);
}

/**
 * Search themes by tag
 */
export function searchByTag(tag: string): ExtractedTheme[] {
  const lowerTag = tag.toLowerCase();
  return EXTRACTED_THEMES.filter((t) =>
    t.tags.some((tg) => tg.toLowerCase().includes(lowerTag))
  );
}

/**
 * Convert HSL string to CSS hsl() format
 */
export function hslToCss(hsl: string): string {
  return `hsl(${hsl})`;
}
